import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {openStorage} from '../storage.mjs';

test('legacy owner migration, invitation registration, session choices and cross-account isolation',async t=>{
 const home=fs.mkdtempSync(path.resolve('test-output/accounts-'));
 const password='Account-test-password-123',salt='legacy-salt',hash=crypto.scryptSync(password,salt,64).toString('hex');
 const oldToken='ab'.repeat(32),digest=crypto.createHash('sha256').update(oldToken).digest('hex');
 const state={revision:7,courses:[],tasks:[{id:'same-task',title:'原来的任务',kind:'project',status:'todo',minutes:60}],ideas:[],blocks:[],reviews:[],settings:{name:'原来的我',semesterStart:'2026-08-31',dayStart:'08:00',dayEnd:'22:00',quietStart:'23:00',quietEnd:'07:00',reminderMinutes:[30],courseReminder:15}};
 const storage=await openStorage({dataDir:home,env:{DB_DRIVER:'sqlite'}});
 await storage.put('account',{username:'student',salt,hash});await storage.put('state',state);
 await storage.db.prepare('INSERT INTO sessions VALUES (?,?)').run(digest,Date.now()+86400000);await storage.db.close();
 const origin='http://localhost:3107';
 const child=spawn(process.execPath,['--import','./tests/mock-ai.mjs','server.mjs'],{env:{...process.env,PORT:'3107',HOST:'127.0.0.1',PUBLIC_ORIGIN:origin,DATA_DIR:home,DB_DRIVER:'sqlite'},stdio:'pipe'});
 let stderr='';child.stderr.on('data',b=>stderr+=b);child.stdout.resume();
 t.after(async()=>{if(child.exitCode===null){const exited=once(child,'exit');child.kill();await exited;}fs.rmSync(home,{recursive:true,force:true});});
 for(let i=0;i<200;i++){try{if((await fetch(origin+'/healthz')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 assert.equal(child.exitCode,null,stderr);
 const call=(route,cookie,body,method=body===undefined?'GET':'POST')=>fetch(origin+route,{method,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{}),Origin:origin},...(body!==undefined?{body:JSON.stringify(body)}:{})});
 const oldCookie='session='+oldToken;
 assert.deepEqual(await(await call('/api/state',oldCookie)).json(),state,'existing tasks and revision survive upgrade');
 const policy=await(await call('/api/registration',oldCookie)).json();assert.equal(policy.mode,'invite');assert.ok(policy.code);
 assert.equal((await call('/api/register',null,{username:'alice',password,code:'wrong'})).status,400);
 for(const username of ['alice','bob'])assert.equal((await call('/api/register',null,{username,password,code:policy.code})).status,201);
 assert.equal((await call('/api/register',null,{username:'ALICE',password,code:policy.code})).status,400,'case variants cannot create duplicate usernames');
 const login=async(username,remember)=>{const r=await call('/api/login',null,{username,password,remember});assert.equal(r.status,200);return {cookie:r.headers.get('set-cookie').split(';')[0],header:r.headers.get('set-cookie')};};
 const alice=await login('alice',true),bob=await login('bob',false);
 assert.match(alice.header,/Max-Age=2592000/i);assert.doesNotMatch(bob.header,/Max-Age|Expires/i);
 assert.match(alice.header,/HttpOnly/i);
 assert.equal((await call('/api/registration',alice.cookie)).status,403);
 assert.equal((await call('/api/development/status',alice.cookie)).status,403);
 assert.equal((await(await call('/api/me',alice.cookie)).json()).username,'alice');
 const aliceID=(await(await call('/api/me',alice.cookie)).json()).id;
 assert.equal((await fetch(origin+'/api/state',{headers:{Cookie:bob.cookie,'X-Shixu-Account':aliceID}})).status,401,'an old tab cannot use its prior account data with a switched cookie');
 const a=await(await call('/api/state',alice.cookie)).json(),b=await(await call('/api/state',bob.cookie)).json();assert.equal(a.tasks.length,0);assert.equal(b.tasks.length,0);
 a.tasks=[{id:'same-task',title:'Alice 私人任务',kind:'project',status:'todo',minutes:30}];
 const updated=await call('/api/state',alice.cookie,a,'PUT');assert.equal(updated.status,200);
 assert.equal((await(await call('/api/state',bob.cookie)).json()).tasks.length,0);
 assert.equal((await(await call('/api/state',oldCookie)).json()).tasks[0].title,'原来的任务');
 const provider=await(await call('/api/providers',alice.cookie,{name:'Alice API',baseUrl:'https://example.com/v1',model:'test',format:'openai',apiKey:'alice-secret'})).json();
 assert.deepEqual(await(await call('/api/providers',bob.cookie)).json(),[]);
 assert.deepEqual(await(await call('/api/providers',oldCookie)).json(),[]);
 const workspace=await(await call('/api/conversations',alice.cookie,{revision:0,action:'createThread',title:'Alice 的对话',projectId:''})).json();
 assert.deepEqual((await(await call('/api/conversations',bob.cookie)).json()).threads,[]);
 const ai=await call('/api/ai/chat',alice.cookie,{providerId:provider.id,threadId:workspace.selectedId,chatRevision:workspace.revision,message:'记个灵感',revision:1});assert.equal(ai.status,200);
 assert.equal((await(await call('/api/state',bob.cookie)).json()).ideas.length,0);
 const capture=await(await call('/api/ai/capture',alice.cookie,{providerId:provider.id,text:'周四去加工，周五交自控作业'})).json();
 assert.equal((await call('/api/ai/capture/apply',bob.cookie,{id:capture.id,items:capture.items})).status,409,'other accounts cannot apply private drafts');
 const sync=(route,body,token)=>fetch(origin+'/api/sync/v1'+route,{method:body===undefined?'GET':'POST',headers:{Origin:'http://localhost:3088','Content-Type':'application/json','X-Shixu-Sync':'1',...(token?{Authorization:'Bearer '+token}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});
 const sa=await(await sync('/login',{username:'alice',password})).json(),sb=await(await sync('/login',{username:'bob',password})).json();
 assert.notEqual(sa.instanceId,sb.instanceId);assert.equal(sa.serverInstanceId,sb.serverInstanceId);
 const deviceId=crypto.randomUUID(),operationId=crypto.randomUUID();
 for(const login of [sa,sb]){
   const snapshot=await(await sync('/state',undefined,login.token)).json();
   const commit=await sync('/commit',{deviceId,operationId,instanceId:login.instanceId,revision:snapshot.state.revision,data:snapshot.state},login.token);
   assert.equal(commit.status,200,'same device and operation are independently scoped');assert.equal((await commit.json()).instanceId,login.instanceId);
 }
 assert.equal((await call('/api/password',oldCookie,{current:password,password:password+'-new'})).status,200);
 assert.equal((await call('/api/state',oldCookie)).status,401,'migration sessions are revoked on password change');
 assert.equal((await call('/api/state',alice.cookie)).status,200,'owner password change leaves other users logged in');
 assert.equal((await call('/api/password',alice.cookie,{current:password,password:password+'-new'})).status,200);
 assert.equal((await call('/api/state',alice.cookie)).status,401);assert.equal((await sync('/state',undefined,sa.token)).status,401);
 assert.equal((await sync('/state',undefined,sb.token)).status,200);
 assert.equal((await call('/api/registration',bob.cookie,{mode:'open'})).status,403);
 await call('/api/logout',bob.cookie,{});assert.equal((await call('/api/state',bob.cookie)).status,401);
});
