import test from 'node:test';
import assert from 'node:assert/strict';
import {autoSyncOnce} from '../public/auto-sync.mjs';
const empty=()=>({revision:0,courses:[],tasks:[],ideas:[],blocks:[],reviews:[],settings:{name:'测试',semesterStart:'2026-08-31',dayStart:'08:00',dayEnd:'22:00',quietStart:'23:00',quietEnd:'07:00',reminderMinutes:[30],courseReminder:15}});
function fixture(){const config={enabled:true,origin:'https://fixture.example',version:1,status:'idle'},preview={base:empty(),local:empty(),remote:empty()};const calls=[];const deps={read:async()=>({...config}),profile:async()=>({base:empty()}),preview:async()=>preview,status:async(v,status)=>{calls.push(status);config.status=status;},acknowledge:async()=>calls.push('ack'),prepare:async()=>calls.push('prepare'),retry:async()=>{calls.push('retry');return preview.local;}};return {config,preview,calls,deps};}
test('automatic sync requires opt-in and pauses until conflicts are manually resolved',async()=>{const f=fixture();f.config.enabled=false;assert.equal((await autoSyncOnce({},f.deps)).kind,'skipped');f.config.enabled=true;f.config.status='conflict';assert.equal((await autoSyncOnce({},f.deps)).kind,'skipped');assert.deepEqual(f.calls,[]);});
test('identical states checkpoint baseline without writing server or local state',async()=>{const f=fixture();assert.equal((await autoSyncOnce({},f.deps)).kind,'unchanged');assert.deepEqual(f.calls,['ack','idle']);});
test('conflicting records pause without choosing a side or sending a commit',async()=>{const f=fixture();const task={id:'a',title:'base',kind:'homework',status:'todo',minutes:30};f.preview.base.tasks=[task];f.preview.local.tasks=[{...task,title:'local'}];f.preview.remote.tasks=[{...task,title:'remote'}];assert.equal((await autoSyncOnce({},f.deps)).kind,'conflict');assert.deepEqual(f.calls,['conflict']);});
test('disabling during a remote read prevents an automatic write',async()=>{const f=fixture();f.deps.preview=async()=>{f.config.enabled=false;return f.preview;};assert.equal((await autoSyncOnce({},f.deps)).kind,'skipped');assert.deepEqual(f.calls,[]);});
test('nonconflicting edits are prepared with the consent version then committed',async()=>{const f=fixture();f.preview.local.ideas=[{id:'i',text:'idea',createdAt:'2026-10-02T00:00:00Z'}];f.deps.prepare=async(origin,preview,data,version)=>{assert.equal(version,1);assert.equal(data.ideas[0].text,'idea');f.calls.push('prepare');};assert.equal((await autoSyncOnce({},f.deps)).kind,'saved');assert.deepEqual(f.calls,['prepare','retry']);});
test('pending request is retried idempotently; network failure waits while expired auth pauses',async()=>{const f=fixture();f.deps.profile=async()=>({base:empty(),pending:{}});f.deps.retry=async()=>{throw new TypeError('Failed to fetch');};assert.equal((await autoSyncOnce({},f.deps)).kind,'waiting');f.deps.retry=async()=>{const e=Error('授权过期');e.status=401;throw e;};assert.equal((await autoSyncOnce({},f.deps)).kind,'attention');});
