import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import http from 'node:http';
import {DatabaseSync} from 'node:sqlite';
import {locations,prepare,importBackup,start,stop} from '../desktop/bootstrap.mjs';
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'shixu-desktop-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const bundle=path.join(root,'bundle');fs.mkdirSync(path.join(bundle,'app'),{recursive:true});fs.writeFileSync(path.join(bundle,'app/package.json'),'{"version":"0.1.0"}');fs.writeFileSync(path.join(bundle,'app/server.mjs'),'original');return {root,bundle,p:locations(bundle,{SHIXU_DESKTOP_HOME:path.join(root,'profile')})};}
test('desktop preparation preserves customized source and keeps data outside the payload',t=>{const {p,bundle}=fixture(t);prepare(p);fs.writeFileSync(path.join(p.workspace,'server.mjs'),'customized');fs.writeFileSync(path.join(bundle,'app/server.mjs'),'upgrade');prepare(p);assert.equal(fs.readFileSync(path.join(p.workspace,'server.mjs'),'utf8'),'customized');assert.ok(!p.data.startsWith(p.workspace+path.sep));assert.throws(()=>prepare({...p,port:3190}),/端口已固定/);});
test('desktop full import copies consistent database and key and refuses replacing existing data',async t=>{const {root,p}=fixture(t);const source=path.join(root,'backup');fs.mkdirSync(source);const db=new DatabaseSync(path.join(source,'planner.sqlite'));db.exec("PRAGMA journal_mode=WAL; CREATE TABLE kv(key TEXT PRIMARY KEY,value TEXT); INSERT INTO kv VALUES ('account','{}'),('state','{\"revision\":7}')");fs.writeFileSync(path.join(source,'secret.key'),Buffer.alloc(32,2));await importBackup(p,source);const copied=new DatabaseSync(path.join(p.data,'planner.sqlite'));assert.equal(JSON.parse(copied.prepare("SELECT value FROM kv WHERE key='state'").get().value).revision,7);copied.close();assert.deepEqual(fs.readFileSync(path.join(p.data,'secret.key')),Buffer.alloc(32,2));await assert.rejects(importBackup(p,source),/已有数据/);db.close();assert.ok(fs.existsSync(path.join(source,'planner.sqlite')));});
test('desktop start and stop refuse an unrelated service on the selected port',async t=>{const {p}=fixture(t);const server=http.createServer((req,res)=>res.end(JSON.stringify({app:'shixu',status:'ok',desktopInstance:'someone-else'})));await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{server.closeAllConnections();server.close();});p.port=server.address().port;p.url=`http://127.0.0.1:${p.port}`;await assert.rejects(start(p),/其他时序/);await assert.rejects(stop(p),/不属于/);assert.ok(server.listening);});
