import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import fs from 'node:fs';
import path from 'node:path';
import ExcelJS from 'exceljs';
const port=Number(process.env.SHIXU_TEST_PORT || 3099), origin=`http://localhost:${port}`;
const testDir=process.env.SHIXU_TEST_DATA_DIR || path.resolve('test-output',`api-${Date.now()}`);fs.mkdirSync(testDir,{recursive:true});
test('authenticated API, cross-device conflicts, submission persistence and key secrecy',async t=>{
  const child=spawn(process.execPath,['--import','./tests/mock-ai.mjs','server.mjs'],{env:{...process.env,PORT:String(port),PUBLIC_ORIGIN:origin,DATA_DIR:testDir,ADMIN_PASSWORD:'Integration-test-password-123'},stdio:'pipe'});
  t.after(async()=>{if(child.exitCode!==null)return;const exited=once(child,'exit');child.kill();await exited;});
  let started=false;let startupError='';child.stderr.on('data',chunk=>startupError+=chunk.toString());
  for(let i=0;i<300;i++){try{const r=await fetch(origin);if(r.ok){started=true;break;}}catch{}await new Promise(r=>setTimeout(r,100));}
  assert.ok(started,'server starts: '+startupError.slice(0,1500));
  const call=async(url,method='GET',body,cookie,extra={})=>fetch(origin+url,{method,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{}),...extra},body:body?JSON.stringify(body):undefined});
  assert.equal((await call('/api/state')).status,401);
  const login=await call('/api/login','POST',{username:'student',password:'Integration-test-password-123'});assert.equal(login.status,200);
  const cookie=login.headers.get('set-cookie').split(';')[0];assert.match(login.headers.get('set-cookie'),/HttpOnly/i);
  const s=await (await call('/api/state','GET',null,cookie)).json();
  const emptyPlan=await call('/api/ai/plan','POST',{},cookie);assert.equal(emptyPlan.status,400);assert.match((await emptyPlan.json()).error,/没有可安排/);
  s.tasks.push({id:'assignment',title:'实验报告',kind:'homework',status:'done',minutes:60,due:'2026-09-08T12:00:00+08:00'});
  let saved=await call('/api/state','PUT',s,cookie);assert.equal(saved.status,200);
  assert.equal((await call('/api/state','PUT',s,cookie)).status,409,'stale device cannot overwrite');
  const updated=await saved.json();updated.tasks[0].status='submitted';updated.tasks[0].submittedAt='2026-09-07T15:03:00+08:00';
  assert.equal((await call('/api/state','PUT',updated,cookie)).status,200);
  const persisted=await (await call('/api/state','GET',null,cookie)).json();assert.equal(persisted.tasks[0].submittedAt,'2026-09-07T15:03:00+08:00');
  assert.equal((await call('/api/state','PUT',persisted,cookie,{Origin:'https://evil.example'})).status,403);
  const provider=await call('/api/providers','POST',{name:'test',baseUrl:'https://example.com/v1',format:'openai',model:'test',apiKey:'secret-for-test'},cookie);assert.equal(provider.status,200);const providerText=await provider.text();assert.ok(!providerText.includes('secret-for-test'));const providerId=JSON.parse(providerText).id;
  assert.ok(!(await (await call('/api/providers','GET',null,cookie)).text()).includes('secret-for-test'));
  assert.equal((await call('/api/ai/apply','POST',{revision:persisted.revision,blocks:[{taskId:'assignment',title:'bad',start:'2026-09-07T12:00:00+08:00',end:'2026-09-07T13:00:00+08:00'}]},cookie)).status,400);
  persisted.tasks.push({id:'project',title:'原型',kind:'project',status:'todo',minutes:60});
  assert.equal((await call('/api/state','PUT',persisted,cookie)).status,200);
  const planResponse=await call('/api/ai/plan','POST',{providerId,prompt:'安排项目'},cookie);assert.equal(planResponse.status,200);
  const plan=await planResponse.json();assert.deepEqual(plan.errors,[]);
  assert.equal((await call('/api/ai/apply','POST',{revision:plan.revision,blocks:plan.blocks},cookie)).status,200);
  assert.equal((await call('/api/ai/apply','POST',{revision:plan.revision,blocks:plan.blocks},cookie)).status,409,'same draft cannot be applied twice');
  const wb=new ExcelJS.Workbook();const sheet=wb.addWorksheet('课表');sheet.addRow(['课程','星期','开始','结束']);sheet.addRow(['测试数学','周一','08:00','09:40']);
  const before=await (await call('/api/state','GET',null,cookie)).json();
  const form=new FormData();form.append('providerId',providerId);form.append('file',new Blob([await wb.xlsx.writeBuffer()]),'courses.xlsx');
  const imported=await fetch(origin+'/api/import',{method:'POST',headers:{Cookie:cookie},body:form});assert.equal(imported.status,200);assert.equal((await imported.json()).courses[0].name,'测试数学');
  const after=await (await call('/api/state','GET',null,cookie)).json();assert.deepEqual(after.courses,before.courses,'import preview does not save without confirmation');
  const backup=await (await call('/api/backup','GET',null,cookie)).json();assert.equal(backup.format,'shixu-backup');assert.ok(!JSON.stringify(backup).includes('secret-for-test'));
  const preview=await (await call('/api/backup/preview','POST',{backup},cookie)).json();assert.equal(preview.counts.tasks,2);
  assert.equal((await call('/api/backup/restore','POST',{backup,revision:preview.revision},cookie)).status,400,'confirmation is mandatory');
  assert.equal((await call('/api/backup/restore','POST',{backup,revision:preview.revision-1,confirmReplace:true},cookie)).status,409,'concurrent changes block stale restore');
  const bad=structuredClone(backup);bad.data.settings.name=null;
  assert.equal((await call('/api/backup/restore','POST',{backup:bad,revision:preview.revision,confirmReplace:true},cookie)).status,400,'invalid import rejected');
  assert.deepEqual(await (await call('/api/state','GET',null,cookie)).json(),after,'failed import leaves data intact');
  backup.data.settings.name='迁移后的同学';
  const restored=await call('/api/backup/restore','POST',{backup,revision:preview.revision,confirmReplace:true},cookie);assert.equal(restored.status,200);assert.equal((await restored.json()).settings.name,'迁移后的同学');
  const previous=await (await call('/api/backup/previous','GET',null,cookie)).json();assert.equal(previous.data.settings.name,after.settings.name);
  assert.equal((await (await call('/api/providers','GET',null,cookie)).json()).length,1,'restore preserves server-local API config');
  const captured=await (await call('/api/ai/capture','POST',{providerId,text:'测试录入两件事'},cookie)).json();assert.equal(captured.items.length,2);assert.deepEqual(captured.issues,[]);
  const addedResponse=await call('/api/ai/capture/apply','POST',{id:captured.id,items:captured.items},cookie);assert.equal(addedResponse.status,200);const added=await addedResponse.json();assert.equal(added.added.length,2);
  assert.equal((await call('/api/ai/capture/apply','POST',{id:captured.id,items:captured.items},cookie)).status,409,'capture cannot apply twice');
  const undone=await call('/api/ai/capture/undo','POST',{id:added.undoId},cookie);assert.equal(undone.status,200);assert.equal((await undone.json()).tasks.length,2);
  assert.equal((await call('/api/ai/capture/undo','POST',{id:added.undoId},cookie)).status,409,'undo cannot run twice');
  const conversations=await (await call('/api/conversations','GET',null,cookie)).json();
  const created=await call('/api/conversations','POST',{revision:conversations.revision,action:'createThread',title:'新对话'},cookie);
  assert.equal(created.status,200);const workspace=await created.json();
  const chatState=await (await call('/api/state','GET',null,cookie)).json();
  const chat=await call('/api/ai/chat','POST',{providerId,revision:chatState.revision,threadId:workspace.selectedId,chatRevision:workspace.revision,message:'记下一个测试灵感'},cookie);
  assert.equal(chat.status,200);const reply=await chat.json();assert.ok(reply.undoId);
  assert.equal((await call('/api/ai/chat/undo','POST',{id:reply.undoId},cookie)).status,200);
  assert.equal((await call('/api/password','POST',{current:'wrong',password:'new-password-is-long'},cookie)).status,400);
  assert.equal((await call('/api/logout','POST',{},cookie)).status,200);
  assert.equal((await call('/api/state','GET',null,cookie)).status,401);
});
